# Code Generated by Sidekick is for learning and experimentation purposes only.
import functions_framework

@functions_framework.http
def app(request):
    """
    HTTP Cloud Function.
    Args:
        request (flask.Request): The request object.
    Returns:
        A plain-text response.
    """
    return "Hello, Cloud Functions (Gen2)!", 200

