# Code Generated by Sidekick is for learning and experimentation purposes only.
from flask import Flask, request

app = Flask(__name__)

@app.route("/", methods=["GET"])
def hello_world():
    return "Hello from Cloud Function v!", 200

